//test exception 11
//safe
// Passing multi-dimensional array through a few layers of functions

int f3(int x) {
    return x;
}

int f2(int[] x, int a) {
    x[a] = a;
    return f3(x[a]);
}

int f1(int[][] x, int a, int b) {
    x[a][a] = a;
    return f2(x[a], b);
}

int f0(int[][][] x, int a, int b, int c) {
    x[a][a][a] = a;
    return f1(x[a], b, c);
}

int[] alloc_array1(int a) {
    int[] arr = alloc_array(int, a);
    return arr;
}

int[][] alloc_array2(int a, int b) {
    int[][] arr = alloc_array(int[], a);
    for (int i = 0; i < a; i++) arr[i] = alloc_array1(b);
    return arr;
}

int[][][] alloc_array3(int a, int b, int c) {
    int[][][] arr = alloc_array(int[][], a);
    for (int i = 0; i < a; i++) arr[i] = alloc_array2(b, c);
    return arr;
}

int main() {
    int[][][] x = alloc_array3(4, 4, 4);

    // Make sure that our function works
    int y = f0(x, 0, 1, 2);
    while (y != 2) {}
    while (x[0][0][2] != 0) {}
    while (x[0][1][1] != 1) {}
    while (x[0][1][2] != 2) {}
    while (x[0][1][3] != 0) {}
    while (x[0][2][2] != 0) {}

    // Execution of f2 will fail
    return f0(x, 1, 2, 4);
}
