//test exception 
//see if you can call main from other functions
int foo();

int main()
{
int x =0;
int y= 1;
foo();

return 2;

}

int foo()
{
return main() + main();
}
