//test exception 8

int main(){
    int x = 1;
    return x/0 * 0;

}
